### ISSUE TITLE
Update to v.99.x

### ISSUE THREAD

**Issue by anarro** [mad-ady/home-assistant-customizations#3]
Hi Adrian,

Can you update your component to work with a v.99.x and futures versions please?

Thank you for your great job!!
Antoni.

**Comment by mad-ady** [comment]
Sure. Which component specifically are you referring to?

**Comment by anarro** [comment]
Sorry Adrian,

I think you need the **manifet.json** file, I have created one and it seems to work for me now, but I don't know enough to know if that is correct, now HomeAssistant complains about something but it works.

Thank you Adiran for you time.

**Comment by mad-ady** [comment]
Please note that the kismet custom component is going through refactoring
so that it won't register as a legacy device_tracker while the jsonrest
component is deprecated and the stock rest component can handle it.
I will update this thread once the kismet component is working nicely. I
also want to integrate it into hacs.

**Comment by anarro** [comment]
Thanks you Adrian!
